development:
  adapter: postgresql
  encoding: unicode
  database: travelmonkey_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: travelmonkey_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: travelmonkey_production
  pool: 5
  username:
  password:
